AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BookTable:
    Type: AWS::Serverless::SimpleTable
  Books:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://upload-something-here-2021/1d4d119674d75e2d73456eded5a6f028
      Handler: books.handler
      Environment:
        Variables:
          TABLE_NAME:
            Ref: BookTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        AddBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
        ListBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
        Book:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: any
